### ISSUE TITLE
Delete row solution

### ISSUE THREAD

**Issue by nacer-rachedi** [sainipray/djadmin#4]
If you get this error : **invalid literal for int() with base 10: '1" class="action-select'**

Solution : 
add this function to : /usr/local/lib/python2.7/dist-packages/djadmin/templatetags/custom.py

`@register.filter
def get_value(result_checkbox_html):
    value = result_checkbox_html.split( )
    for x in value:
        if x.startswith("value"):
            val = x.split("=")
            return val[1].replace('"','')
    return None
`

and go to this file : /usr/local/lib/python2.7/dist-packages/djadmin/templates/admin/change_list_results.html

replace this "**admin_change_list_value**" with "**get_value**"

**Comment by sainipray** [comment]
Can you send full traceback of this error?
are you getting this error on demo site https://djadmin.herokuapp.com/en/admin?

**Comment by nacer-rachedi** [comment]
i can't access to the demo page 
i got this error : **permission denied for relation django_session**
Exception Location:	/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py in execute, line 64

this error that i'm talking you about , occurs when deleting data from admin panel
the full trace back : 

## Traceback Switch to copy-and-paste view

/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py in inner
            response = get_response(request) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in _get_response
                response = self.process_exception_by_middleware(e, request) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in _get_response
                response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py in wrapper
                return self.admin_site.admin_view(view)(*args, **kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py in _wrapped_view
                    response = view_func(request, *args, **kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py in _wrapped_view_func
        response = view_func(request, *args, **kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py in inner
            return view(request, *args, **kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/djadmin/mixins.py in changelist_view
        return super(DjadminMixin, self).changelist_view(request, extra_context=extra_context) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py in _wrapper
            return bound_func(*args, **kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py in _wrapped_view
                    response = view_func(request, *args, **kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py in bound_func
                return func.__get__(self, type(self))(*args2, **kwargs2) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py in changelist_view
                response = self.response_action(request, queryset=cl.get_queryset(request)) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py in response_action
                queryset = queryset.filter(pk__in=selected) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/query.py in filter
        return self._filter_or_exclude(False, *args, **kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/query.py in _filter_or_exclude
            clone.query.add_q(Q(*args, **kwargs)) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py in add_q
        clause, _ = self._add_q(q_object, self.used_aliases) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py in _add_q
                    allow_joins=allow_joins, split_subq=split_subq, ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py in build_filter
            condition = self.build_lookup(lookups, col, value) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py in build_lookup
                return final_lookup(lhs, rhs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/lookups.py in __init__
        self.rhs = self.get_prep_lookup() ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/lookups.py in get_prep_lookup
                rhs_value = self.lhs.output_field.get_prep_value(rhs_value) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py in get_prep_value
        return int(value) ...
▶ Local vars

**Comment by nacer-rachedi** [comment]
there is an other problem after closing combo box , the page behaves like the combobox is still open
please can you help me with this issue
if i get any solution for this i will poste it as soon as i can
thanks ,

**Comment by nacer-rachedi** [comment]
about the combobox issue you can solve it by doing as follows:
go to
/usr/local/lib/python2.7/dist-packages/djadmin/static/admin/css/custom.css
line 958
set display to none
form .related-widget-wrapper ul {
    display: none;
    margin-left: 0;
    padding-left: 0;
}

**Comment by sainipray** [comment]
Hi @nacer-rachedi Thanks for comment. 
**Deleteing row issue** that I already fixed in 

> "Fixed Sortable Issue" commit 

 [https://github.com/sainipray/djadmin/commit/3fb68e3d38cde1dd9a966cf555ede876a9475b2f](commit) 
and combobox CSS issue I fixed. Upgrade djadmin lib in your project you won't get again above issues.
